In [1]:
import numpy as np
import pandas as pd
import math

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Ковариация:

In [4]:
cov_1 = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov_1

9157.839999999997

In [5]:
cov_2 = np.cov(zp, ks, ddof=0)
cov_2

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Коэффициент корреляции:

In [6]:
np.cov(zp, ks)/(np.std(zp, ddof=1)*np.std(ks, ddof=1))

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [7]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [8]:
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
x

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [9]:
X = np.mean(x)
X

118.1

In [10]:
std = np.std(x, ddof=1)
std

10.54566788359614

In [11]:
118.1 + 2.262*(std/(10**0.5))

125.64339223691834

In [12]:
118.1 - 2.262*(std/(10**0.5))

110.55660776308164

3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [13]:
174.2 + 1.96*(5/(27**0.5))

176.08601087935276

In [14]:
174.2 - 1.96*(5/(27**0.5))

172.31398912064722