In [1]:
import numpy as np
from scipy import stats

In [4]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [5]:
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [6]:
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [7]:
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)